name: test

on:
  pull_request:
    
jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run unit tests
        run: |
          xcrun simctl list devices
          xcodebuild clean test -project "SimpleChat.xcodeproj" -scheme "SimpleChat" -destination "platform=iOS Simulator,name=iPhone 11 Pro,OS=14.3" 
