name: test

on:
  pull_request:
    
jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare simulator
        run: |
          sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes
          sudo ln -s /Applications/Xcode_12.3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS\ 14.3.simruntime
          xcrun simctl list runtimes
          xcrun simctl create custom-test-device "iPhone 11 Pro Max" "com.apple.CoreSimulator.SimRuntime.iOS-14-3"
          xcrun simctl list devices 14.3
      - name: Run unit tests
        run: xcodebuild clean test -project "SimpleChat.xcodeproj" -scheme "SimpleChat" -destination "platform=iOS Simulator,OS=14.3,name=custom-test-device" 
