name: Tests

on: push
    
jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Switch to Xcode
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      - name: Run tests
        run: xcodebuild clean test -project "SimpleChat.xcodeproj" -scheme "SimpleChat" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=14.4"
